"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-04-19 16:17:24.061143+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'QUALIFIED', 'ABANDONED', name='conversation_status'), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=True),
    sa.Column('final_tier', postgresql.ENUM('TIER_1', 'TIER_2', 'TIER_3', 'UNQUALIFIED', name='lead_tier'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_status_created_at', 'conversations', ['status', 'created_at'], unique=False)
    op.create_table('agent_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_agent_traces_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_traces'))
    )
    op.create_index(op.f('ix_agent_traces_conversation_id'), 'agent_traces', ['conversation_id'], unique=False)
    op.create_table('lead_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('business_segment', postgresql.ENUM('INDUSTRIAL', 'COMMERCIAL', name='business_segment'), nullable=True),
    sa.Column('annual_usage_mwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contract_status', postgresql.ENUM('EXPIRING_SOON', 'EXPIRING_WITHIN_YEAR', 'MONTH_TO_MONTH', 'FIXED_TERM', 'NO_PROVIDER', name='contract_status'), nullable=True),
    sa.Column('building_age_years', sa.Integer(), nullable=True),
    sa.Column('square_footage', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('usage_was_estimated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_lead_profiles_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_profiles')),
    sa.UniqueConstraint('conversation_id', name=op.f('uq_lead_profiles_conversation_id'))
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('qualification_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('event_type', postgresql.ENUM('VARIABLE_COLLECTED', 'FALLBACK_TRIGGERED', 'ESTIMATION_APPLIED', 'TIER_DETERMINED', name='event_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_qualification_events_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qualification_events'))
    )
    op.create_index(op.f('ix_qualification_events_conversation_id'), 'qualification_events', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualification_events_conversation_id'), table_name='qualification_events')
    op.drop_table('qualification_events')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('lead_profiles')
    op.drop_index(op.f('ix_agent_traces_conversation_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index('ix_conversations_status_created_at', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###